name: Version Update Workflow

'on':
  push:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Create a new branch and push the changes to it.
        run: |
          export VERSION=$(git log -1 --format=%cd --date=format:v%Y-%m-%d-%H%M%S)
          
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"

          git checkout -b version/$VERSION
          git commit --allow-empty -am 'Version update'
          git push -u origin version/$VERSION
